//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDMS.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class ADA
    {
        public ADA()
        {
            this.DSTRCTs = new HashSet<DSTRCT>();
        }
    
        public int adaid { get; set; }

        [Required]
        public string adaname { get; set; }
    
        public virtual ICollection<DSTRCT> DSTRCTs { get; set; }
    }
}
