//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDMS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AGEGROUP
    {
        public AGEGROUP()
        {
            this.VARIETies = new HashSet<VARIETY>();
        }
    
        public int agegroupid { get; set; }
        public string agegroupname { get; set; }
    
        public virtual ICollection<VARIETY> VARIETies { get; set; }
    }
}
