//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDMS.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    
    public partial class AILIST
    {
        public AILIST()
        {
            this.MAJORPADDies = new HashSet<MAJORPADDY>();
            this.MINORPADDies = new HashSet<MINORPADDY>();
            this.RAINFEDPADDies = new HashSet<RAINFEDPADDY>();
        }
    
        public int aiid { get; set; }
        public int ascid { get; set; }

        [Required]
        [Display(Name="AI Range")]
        public string airange { get; set; }

        [Required]
        [Display(Name="Name")]
        public string ainame { get; set; }

        [Required]
        [StringLength(10)]
        [RegularExpression(@"^[0-9]{9}[vVxX]$", ErrorMessage="Invalid NIC number")]
        public string nic { get; set; }

        
        //[RegularExpression(@"^\d{10}$", ErrorMessage = "Characters are not allowed.")]
        [RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$", ErrorMessage = "Invalid phone number")]
        [Display(Name="Telephone")]
        public string telephone { get; set; }

        [Required]
        [EmailAddress]
        [Display(Name="Email")]
        public string email { get; set; }
    
        public virtual ASC ASC { get; set; }
        public virtual ICollection<MAJORPADDY> MAJORPADDies { get; set; }
        public virtual ICollection<MINORPADDY> MINORPADDies { get; set; }
        public virtual ICollection<RAINFEDPADDY> RAINFEDPADDies { get; set; }
    }
}
