//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDMS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DSTRCT
    {
        public DSTRCT()
        {
            this.DS = new HashSet<D>();
        }
    
        public int districtid { get; set; }
        public int adaid { get; set; }
        public string districtname { get; set; }
    
        public virtual ADA ADA { get; set; }
        public virtual ICollection<D> DS { get; set; }
    }
}
