//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDMS.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CDMSEntities2 : DbContext
    {
        public CDMSEntities2()
            : base("name=CDMSEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADA> ADAs { get; set; }
        public virtual DbSet<AGEGROUP> AGEGROUPs { get; set; }
        public virtual DbSet<AILIST> AILISTs { get; set; }
        public virtual DbSet<ASC> ASCs { get; set; }
        public virtual DbSet<D> DS { get; set; }
        public virtual DbSet<DSTRCT> DSTRCTs { get; set; }
        public virtual DbSet<MAJORPADDY> MAJORPADDies { get; set; }
        public virtual DbSet<MINORPADDY> MINORPADDies { get; set; }
        public virtual DbSet<MONTH> MONTHS { get; set; }
        public virtual DbSet<RAINFEDPADDY> RAINFEDPADDies { get; set; }
        public virtual DbSet<SEASON> SEASONS { get; set; }
        public virtual DbSet<VARIETY> VARIETies { get; set; }
        public virtual DbSet<YEAR> YEARS { get; set; }
    }
}
