//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDMS.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class MONTH
    {
        public MONTH()
        {
            this.MAJORPADDies = new HashSet<MAJORPADDY>();
            this.MINORPADDies = new HashSet<MINORPADDY>();
            this.RAINFEDPADDies = new HashSet<RAINFEDPADDY>();
        }
    
        public int monthid { get; set; }

        [Display(Name="Month")]
        public string monthname { get; set; }
        public int seasonid { get; set; }
    
        public virtual ICollection<MAJORPADDY> MAJORPADDies { get; set; }
        public virtual ICollection<MINORPADDY> MINORPADDies { get; set; }
        public virtual SEASON SEASON { get; set; }
        public virtual ICollection<RAINFEDPADDY> RAINFEDPADDies { get; set; }
    }
}
