//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDMS.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class SEASON
    {
        public SEASON()
        {
            this.MONTHS = new HashSet<MONTH>();
        }
    
        public int seasonid { get; set; }

        [Display(Name="Season")]
        public string seasonname { get; set; }
    
        public virtual ICollection<MONTH> MONTHS { get; set; }
    }
}
