//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDMS.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class VARIETY
    {
        public VARIETY()
        {
            this.MAJORPADDies = new HashSet<MAJORPADDY>();
            this.MINORPADDies = new HashSet<MINORPADDY>();
            this.RAINFEDPADDies = new HashSet<RAINFEDPADDY>();
        }
    
        public int varietyid { get; set; }
        public string varietyname { get; set; }
        public int agegroupid { get; set; }
    
        public virtual AGEGROUP AGEGROUP { get; set; }
        public virtual ICollection<MAJORPADDY> MAJORPADDies { get; set; }
        public virtual ICollection<MINORPADDY> MINORPADDies { get; set; }
        public virtual ICollection<RAINFEDPADDY> RAINFEDPADDies { get; set; }
    }
}
